name: GraphQL API Documentation new
run-name: ${{ github.actor }} is running GraphQL API Doc Generator

on:
  workflow_dispatch:
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Hello Command
        run: echo "Hello"
