name: Test-Branch1
on:
  push:
    branches:
      - workflows-testing
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Hello Command
        run: echo "Hello"
